version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client/web/react"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/agent/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
permissions:
  security-events: write
  contents: read